export enum AbilityActionType {
  CLASSROOM = 'CLASSROOM',
  ASCENSION = 'ASCENSION',
  THEFT = 'THEFT',
  REVEAL = 'REVEAL',
  HEALTH = 'HEALTH',
  REVIVE = 'REVIVE',
  DEFEREAL_HOMEWORK = 'DEFEREAL_HOMEWORK'
}
