export enum AbilityType {
  DAMAGE = 'DAMAGE',
  HELP_CLASSMATE = 'HELP_CLASSMATE',
  BENEFIT = 'BENEFIT',
  PROTECT = 'PROTECT',
  STRATEGIC = 'STRATEGIC',
  MULTIPLE_BENEFITS = 'MULTIPLE_BENEFITS',
  MULTIPLE_ATTACKS = 'MULTIPLE_ATTACKS'
}
